### ISSUE TITLE
Provide custom.css and custom.js for easy customization without building

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/hummingbird#126]
A lot of merchants (or their store managers) need just some minor overrides in the default template and it's enough for them. They don't have the time and skills to set up build environment recompile their CSS. We should ship the theme with a place for them to enter their own custom styles and scripts.

See
https://github.com/prestarocket-agence/classic-rocket/blob/master/assets/css/custom.css
https://github.com/prestarocket-agence/classic-rocket/blob/master/assets/js/custom.js

**Comment by rodriciru** [comment]
Thaths not child-parent theme feature which can be donde in BO whitout need to compile anything?

**Comment by alfonsolr09** [comment]
> They don't have the time and skills to set up build environment recompile their CSS.

You can add changes or code to theme.css.  Right?

**Comment by SharakPL** [comment]
> > They don't have the time and skills to set up build environment recompile their CSS.
> 
> You can add changes or code to theme.css.  Right?

No, you can't. This file is recompiled from .scss on each webpack build so any manual addition to theme.css would be erased.

**Comment by PrestaEdit** [comment]
Theses files (custom.css|js) doesn't need to be part of the theme. It's not the good behavior, the theme need to be delivered without them or at the next update of it, it will overwrite the existing files.

**Comment by SharakPL** [comment]
Would be best to have custom css and js editable inside admin panel on per-theme basis.

**Comment by NeOMakinG** [comment]
@PrestaShop/prestashop-maintainers , need your advice on this

**Comment by PrestaEdit** [comment]
The assets custom.js and custom.css are loaded inside the FrontController by default, with the lower priority. (https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/FrontController.php#L939)

It's means that even if you don't create it firstly in your theme, the add of theses files inside your main theme or the child theme will load them into your shop.

If you add theme inside the theme, once you will apply the update, files will be overwritten (and since we have no tools to apply a theme update, there is nothing make to ignore theses files to be overwritten).

For me, theses files doesn't need to be there, even empty.

**Comment by kpodemski** [comment]
I agree with @PrestaEdit - FrontController already loads these files. If you want to improve this, there might be a chance to create a tool to edit these files with a nice code editor.

**Comment by alfonsolr09** [comment]
so if someone wants to make small changes to the theme, how will it be done?

**Comment by kpodemski** [comment]
Simply create custom.js and custom.css so they can be loaded via FrontController

**Comment by SharakPL** [comment]
[Ace](https://ace.c9.io/) looks promissing for an embeded code editor and it's actively maintained.

**Comment by NeOMakinG** [comment]
I guess we can close this issue as the feature is already present in the `FrontController`
