### ISSUE TITLE
Usage of ps_banner inside theme

### ISSUE THREAD

**Issue by Oksydan** [PrestaShop/hummingbird#268]
We shouldn't set fixed with/height and force image ratio inside template.
Merchant should be able to use any image.

**Comment by NeOMakinG** [comment]
@Oksydan Thought about it.

Do we have some cases where the default value would be empty? I would like to avoid having layout shifts because of this, setting width/height will tell the browser to leave this empty space for the image. Just want to be sure that `ps_banner` has a default value on width/height, and then if merchants decide to remove it, it's their own responsibility

**Comment by Oksydan** [comment]
@NeOMakinG we don't need default width/height when new version of ps_banner will be released. If file exists width/height will be set properly.  
Ping someone responsible for it, multiple fixes are merged there.

**Comment by NeOMakinG** [comment]
I did release the module, I'll provide a PR to fix these fixed dimensions
