### ISSUE TITLE
Layout seems broken

### ISSUE THREAD

**Issue by bastijan** [PrestaShop/hummingbird#290]
The default installation of Hummingbird gives me a broken layout:

[Hummingbird Theme https://pasteboard.co/NJau58dlgC4g.png](https://pasteboard.co/NJau58dlgC4g.png)

cache  cleared, layout is "full width"

With the Classic theme, the slider is centered on page:

[Classic Theme https://pasteboard.co/AisF74DcDYMw.png](https://pasteboard.co/AisF74DcDYMw.png)

**Comment by Hlavtox** [comment]
I don't understand what is the problem. Full width = full width. 🤷🏻‍♂️

**Comment by bastijan** [comment]
If you can't see difference between two screenshots I can't help you to understand.

**Comment by bastijan** [comment]
I honestly don't like PrestaShop at all, but that's a client's request.

Let's learn to write software.

**Comment by mparvazi** [comment]
Hummingbird is WIP
There is minor bugs that need to be fixed.

**Comment by Hlavtox** [comment]
> If you can't see difference between two screenshots I can't help you to understand.

I see correct behavior in the new theme. If full width on classic was centered, it was wrong.

> I honestly don't like PrestaShop at all, but that's a client's request.

Then use a different software a don't spread bad mood. :-)))

And don't talk to me like this, I am not the one to try it on.

**Comment by NeOMakinG** [comment]
Hello @bastijan 

This is because the default `banner` image hasn't been changed on the core side.

The layout of `Hummingbird` is different from `classic`, it's mainly full-width everywhere. I don't see anything wrong with that screenshot at the moment.

Remember that hummingbird is a WIP, you probably shouldn't use it for a client.

And please guys, be kind to each other and respect the time of everyone building things, if you don't like it, don't use it and let your client find another agency/freelance.
