### ISSUE TITLE
Bad display of password strength alerts

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/hummingbird#337]
![Screenshot from 2022-07-07 17-40-45](https://user-images.githubusercontent.com/85633460/177782235-bf5dba52-2ce1-4309-b437-b2d4bdd78394.png)

No enough spacing on top, easy to fix, but I have concern about the way alerts appears to the customers.
3 danger alerts? It seems customer did a crime!
This is not the cpanel or admin login page that security is vital, we should display these notifications in a friendly way.

**Comment by SharakPL** [comment]
Yeah, definitely isn't good enough this way. Should be one alert box with a list of issues.

**Comment by Hlavtox** [comment]
We can use the bootstrap styling of errors instead of the alert maybe, would look better. ;)

**Comment by matks** [comment]
> 3 danger alerts? It seems customer did a crime!

Bad password -> straight to prison 🚔

**Comment by mparvazi** [comment]
@NeOMakinG 

Wdyt?
![Screenshot from 2022-07-08 14-23-46](https://user-images.githubusercontent.com/85633460/177967207-e98dfd0f-617f-4caf-84b6-82769431e562.png)

**Comment by NeOMakinG** [comment]
Go for it!

**Comment by SharakPL** [comment]
Where translations for these are maintained? Polish needs some improvements here because of different phrases used based on the number of errors:
_"Jest 1 błąd:"
"Są 2/3/4 błędy:"
"Jest 5/6/.... błędów:"_

Or it could be simplyfied"
```smarty
{l s='Errors count:' d='Shop.Notifications.Error'} {$errors|count}
```
so it would work for all:
_"Liczba błędów: 1/2/3/..."_

**Comment by SharakPL** [comment]
> I think you can play with %d% position on translation line. like this `Liczba błędów: %d%`

I know I can. That's why I wanted to know where to change the translations. [Already got my answer on slack.](https://crowdin.com/project/prestashop-official) 
Besides I generally try to avoid sprintf in templates whenever possible and make translations more technical (_phrase-to-translate: {$variable}_). This will always work as expected no matter the language specs.

**Comment by Hlavtox** [comment]
@SharakPL Translating our languages is not fully supported :(, I opened a topic about this some time ago - https://github.com/PrestaShop/PrestaShop/issues/15870

**Comment by SharakPL** [comment]
I'm aware and honestly I can't see any good solution for that other than make it as technical as possible. eg. (polish) instead of:

> 0 produktów
> 1 produkt
> 2/3/4 produkty
> 5/6/... produktów

should be simply _Products count: 0/1/2/3/4/..._

> Liczba produktów: 0/1/2/3/4/...

but some languages probably have different ranges than 0 / 1 / 2-4 / 5 - ∞ so making it this way still wouldn't fix the problem for all and only made it more difficult for others that don't use all these ranges 😕

Anyway let's keep this discussion in your opened issue.
