### ISSUE TITLE
gap property for Flexbox (Safari)

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/hummingbird#354]
The `gap` property has been supported after Safari 14.5 (2021)
Currently used for buttons with icon.
So need to revert this implementation (I think doesn't works for iPhone older than 11).

![Screenshot 2022-07-18 at 16-03-55 Safari version history - Wikipedia](https://user-images.githubusercontent.com/85633460/179554294-5a083a87-c000-48f9-83e8-71e362f34f49.png)

![Screenshot 2022-07-18 at 16-04-41 gap Can I use  Support tables for HTML5 CSS3 etc](https://user-images.githubusercontent.com/85633460/179554316-0c5e7fc6-06d1-426a-b67e-7ddb5f1697f9.png)

**Comment by SharakPL** [comment]
No need. [Usage of these versions](https://browserslist.dev/?q=ZGVmYXVsdHM%3D) is similar to IE11 and since Bootstrap 5 drops support for IE11, which is oficially dead now, then I don't see the reason we should still support old Safari.

![obraz](https://user-images.githubusercontent.com/5007456/179572029-1d6dc03a-3347-43f1-bab8-cbc938139ed9.png)

**Comment by mparvazi** [comment]
bootstrap 5.0 / .browserslistrc 

```
>= 0.5%
last 2 major versions
not dead
Chrome >= 60
Firefox >= 60
Firefox ESR
iOS >= 12
Safari >= 12
not Explorer <= 11
```

gap

```
Safari >= 14.5
```

**Comment by SharakPL** [comment]
Fair point, but we shouldn't drop modern css just because some old browsers with marginal use don't support it. Last update of Bootstrap's .browserslistrc was 16 months ago. Besides the only problem with this is that icon will be closer to the button text. IMO it's not worth the trouble.

Anyway there are [some workarounds](https://github.com/w3c/csswg-drafts/issues/3559), but I would rather switch to Grid instead Flex. Even [Safari 12 supports](https://caniuse.com/mdn-css_properties_gap_grid_context) `gap` in Grid

**Comment by NeOMakinG** [comment]
I guess it's fine if we don't support Safari < 14.4
