### ISSUE TITLE
Provide a build zip including assets when merging on the main branch

### ISSUE THREAD

**Issue by keshvathakur47** [PrestaShop/hummingbird#361]
When you try to install the theme without building assets, you'll get an error:

`An error occurred. The template "assets/css/theme.css" is missing.`

We need a way to install the theme without building assets, even if it's not stable yet

**Comment by NeOMakinG** [comment]
> An error occurred. The template "assets/css/theme.css" is missing.

Hi @keshvathakur47 , you need to build the theme assets before installing, that's why :)

Currently, there is no build zip ready for production, you've to do it manually!

**Comment by prestasupport** [comment]
Need to create manually  assets/css/ theme.css these file and folder ?

**Comment by NeOMakinG** [comment]
> Need to create manually assets/css/ theme.css these file and folder ?

At the moment, you've to build the assets (because we don't provide any zip including them and we don't want to push them to the repository to keep a smoother dev experience as it avoid a lot of conflicts

You can find the build instruction there: https://github.com/PrestaShop/hummingbird#how-to-build-assets

When the theme will be released as stable, we will obviously provide a zip of the stable version, including assets! But as it's a WIP version, it's not done yet :)

**Comment by NeOMakinG** [comment]
I'm opening again but changing the title and content of the issue because we need to tweak the CI to provide a zip on merge on the main branch!

**Comment by prestasupport** [comment]
You have video where run these commend 

in theme folder ?
in server root dir ?
theme dir ?

which place run commend
