### ISSUE TITLE
[FO] CART-  Wrong behavior when there are more items than there are in stock

### ISSUE THREAD

**Issue by Zoefinders** [PrestaShop/hummingbird#485]
### Describe the bug

In cart page, when you add more items than in stock, they are added and only warning popup is displayed.

### Expected behavior

The warning popup should be displayed as an error popup with red color and same content, and the quantity shound't be updated. 

### Steps to reproduce 

1. BO>create a product with qty=5
2. FO> add 5 of this product to the cart
3. Check the cart and try to add another one
4. A warning popup is displayed => Error (should be an error popup)
5. See error => The qty of product is updated and is displayed as 6

**Screen record**

[hb_cart.webm](https://github.com/PrestaShop/hummingbird/assets/23308427/ecf755b5-54fa-4d68-a647-68a98dc1233a)

### Additional infos

- HummingBird version: develop
- PS version: develop
- PHP version: 7.4

**Comment by ga-devfront** [comment]
@Zoefinders is it possible to know what we need to display (mockup or more detailed description, maybe) ?

**Comment by Hlavtox** [comment]
@ga-devfront I would use a toast with some error message. https://build.prestashop-project.org/hummingbird/?path=/story/ui-toasts--extended-toasts

Check if some nice error is coming with the response from the core. If not, we will find some string to display on theme side.

I am not sure how well big role https://github.com/PrestaShop/ps_shoppingcart/ plays in this behavior. The module may need to be updated. 👍

**Comment by Hlavtox** [comment]
@Zoefinders The confirmation popup is handled by the https://github.com/PrestaShop/ps_shoppingcart/ module, so if TPL modification is not enough, maybe the module will need to be modified to handle the response from the core better.

**Comment by tajriba** [comment]
hi,
we can also add more products to the cart from the product detail page (hummingbird+prestashop 801).
I see no fixes for this in prestashop 802.

**Comment by ga-devfront** [comment]
Hello everyone !
I may have found a solution to our problem by changing the TPL and JS a bit.
However, I would like to have more precision on what is expected.

**Currently on Hummingbird** => It is possible to go above the quantity in stock (even if the merchant does not allow it in the BO), this generates a toast (warning) and the checkout button is always active.

**Currently on the classic** =>  It is possible to go above the quantity in stock (even if the merchant does not allow it in the BO), this generates an alert in top of cart (danger) and the checkout button is disabled.

**What is possible** => Prevent from being able to go above the quantity in stock (when the merchant blocks the possibility of doing so from the BO), if the user tries, he is at a danger toast (it is also possible to put an alert directly above of the product in question). Since the quantity is always good, the checkout button remains active. If there is a modification of stocks between two loading, the checkout button can be deactivated.

I await your feedback as soon as possible in order to finalize the fix.

**Comment by EmnaChou** [comment]
i m going to test this PR

**Comment by tswfi** [comment]
I can't replicate this with prestashop 8.1.2 and develop branch of hummingbird. 
The notification is shown and qty is changed to what ever the limit is.

One thing with the notification is that they do not have a "timeout" so you can have quite a few of them after just a few tests :D

![image](https://github.com/PrestaShop/hummingbird/assets/1352132/e9d903e6-d878-442b-811a-c76177bdec99)

**Comment by florine2623** [comment]
Closing this issue as it is fixed in branch develop of hummingbird :


https://github.com/PrestaShop/hummingbird/assets/16019289/cc7097f6-cb27-4279-8b45-bcd48fa615e3
