### ISSUE TITLE
[FO] CART- When your add more items to cart than is in stock there are few issues

### ISSUE THREAD

**Issue by Zoefinders** [PrestaShop/hummingbird#488]
### Describe the bug

When your add more items to cart than is in stock there are few issues

### Steps to reproduce

1. BO > Update the `Mug The best is yet to come` quantity to 1 and save
2. FO > Add one `Mug The best is yet to come` to the Cart
3. Access to the cart page
4. Try to add more of `Mug The best is yet to come` to the cart 
5. You can see the message `The available purchase order quantity for this product is 1.` displayed, but you don't know how many pieces are in stock.
6. Change the quantity, the error disappears, only a toast is shown in top right.
7. Even though there is an error the `Proceed to checkout` is active.
8. When you click it, you stay on the same page, but the red error disappears.
9. When you add another product that is in stock, go to cart, delete this instock product, the red error disappears.

**Screen record**
[error-msg-cart.webm](https://github.com/PrestaShop/hummingbird/assets/23308427/d00b89a1-8d50-41f0-bce4-bf10acd52fdc)

### Additional infos

- HummingBird version: 0.1.5
- PS version: develop
- PHP version: 8.0

**Comment by ga-devfront** [comment]
@Zoefinders 
> You see Mug The best is yet to come is no longer available in this quantity. You cannot proceed with your order until the quantity is adjusted., but you don't know how many pieces are in stock.

Is it possible to get the good sentence you want with the quantity ?

> You change quantity, the error disappears, only a toast is shown in top right.

Impossible to reproduce the error, rest.

**Comment by hibatallahAouadni** [comment]
Can't reproduce

**Comment by GytisZum** [comment]
## **Hello,**
#### I would like to get some more information about expected behavior;

## **Steps:**

1. - [x] **BO > Update the Mug The best is yet to come quantity to 1 and save**  
2. - [x] **FO > Add one Mug The best is yet to come to the Cart**
3. - [x] **Access to the cart page**
4. - [x] **Try to add more of Mug The best is yet to come to the cart**
5. - [ ] **You can see the message The available purchase order quantity for this product is 1. Is displayed, but you don't know how many pieces are in stock.**
![Image](https://github.com/PrestaShop/hummingbird/assets/96050852/9ff06cee-124e-4bcc-9458-d9678dbee850)
Toast show how many products are in stock. If it is not the right way to show stock please be more precise how many pieces are in stock.
6. - [ ] **Change the quantity, the error disappears, only a toast is shown in top right.**
As you can see error never exist on this version of prestashop.
7. - [x] **Even though there is an error the Proceed to checkout is active.**
This issue exist and I have solution to fix it already.
![Image](https://github.com/PrestaShop/hummingbird/assets/96050852/169adc28-873f-4969-a7c3-ed829217d21c)
8. - [x] **When you click it, you stay on the same page, but the red error disappears.**
The button is not clickable anymore as it is disabled.
9. - [ ] **When you add another product that is in stock, go to cart, delete this in stock product, the red error disappears.**
Error above product does not exist.

## Worth to mention:
If cart page contains product which has incorrect quantity and its not allowed to order error message appears.
#### Bad quantity (button disabled):
![Image](https://github.com/PrestaShop/hummingbird/assets/96050852/2f4fab1d-cd82-4762-b69c-96856e4c0c27)

#### Good quantity (button enabled):
However this error message never disappear even if I lower the quantity to the correct one.
![Image](https://github.com/PrestaShop/hummingbird/assets/96050852/6adeae7a-67cc-4a38-8623-508d3fb940ca)

As you can see error message still exist.


#### Additional information:
    HummingBird version: 0.1.5
    PS version: 8.1.0
    PHP version: 8.0

**Comment by tajriba** [comment]
@ga-devfront hi, i want this also fixed for 8.0.X .
It works on the checkout/cart pages these changes.
But on the product page, it still add's the product to the cart. For example I have 5 quantity in stock, I can add 6 to the cart on the product detail page,  Any idea how to get it working also for 8.0.X ?
