### ISSUE TITLE
[UNFINISHED THINGS]  - Sytle product comment

### ISSUE THREAD

**Issue by Zoefinders** [PrestaShop/hummingbird#494]
![Image](https://user-images.githubusercontent.com/99200820/236134273-300aa10b-b1e2-4ab0-90ad-a4d8a870dc2e.png)

**Comment by SharakPL** [comment]
IMO comments should be included into accordion. Title: Reviews.

**Comment by ElodieOS** [comment]
This is my proposition for this issue
![image](https://github.com/PrestaShop/hummingbird/assets/113457393/0c6b30a8-c06c-41b9-8dc9-8c428c3177b1)

**Comment by Hlavtox** [comment]
@ElodieOS Love it, clean. :-)

**Comment by pawelkierklo** [comment]
In practical terms:

- Consider displaying comments with just one combined field for the title and comment. This streamlining approach enhances readability and reduces visual clutter.
- Implement a 'Read More' button directly following the text, ensuring that users can effortlessly access additional content without interruption.
- Remove the 'Report' button. Ensure that all website features align with the overall user experience and functionality.
- Explore the possibility of arranging comments in a column format, preferably positioned after the Technical Sheet. This organization enhances user comprehension and navigation.

These suggestions aim to enhance the website's usability and user-friendliness, ultimately providing a more intuitive and efficient browsing experience for users.

**Comment by ElodieOS** [comment]
Hello @pawelkierklo! 
Thanks for your feedbacks, they're very interesting. 

First of all, I agree with the idea of placing the "read more" button directly after the text. As you said, it's easier for the user to access additional content without stopping reading. 

For the last two suggestions, I don't know if we can do anything as I think they're linked to the module (product comments). For the positioning, I think it's because the module uses a hook that's here. 
So I don't know if we can change these two points.
