### ISSUE TITLE
[DESKTOP - Checkout Page] Step 1: Billing information

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/hummingbird#5]
Epic: https://github.com/PrestaShop/theme-refacto/issues/2
Responsive's issue: https://github.com/PrestaShop/theme-refacto/issues/12

[Link to Figma prototype](https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?node-id=2351%3A24213)

#### Mockups

**Comment by NeOMakinG** [comment]
I guess this is done, if there are some things to polish, let's see this after product review

PS: If we want to simplify the purchase, some core reworks are needed, the actual version of hummingbird should work with both 1.7.8 and 8.0 and the checkout rework of the core isn't in the roadmap, if you wan't to improve something, don't hesitate to create an issue on the core repository in order to discuss about it and integrate it to the roadmap
